CREATE DATABASE GCosmetics;

DROP TABLE IF EXISTS DescriptionSale;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Sale;

CREATE TABLE Sale(
    NumberSale INT AUTO_INCREMENT,
    SubTotal INT NOT NULL,
    TotalIVA INT NOT NULL,
    Total INT NOT NULL,
    CreationDate TIMESTAMP NOT NULL,
    NameUser VARCHAR(100) NOT NULL,
    PRIMARY KEY(NumberSale)
);

CREATE TABLE Product(
    Id INT UNSIGNED AUTO_INCREMENT,
    Description varchar(100) NOT NULL,
    Price INT UNSIGNED NOT NULL,
    Existence INT UNSIGNED NOT NULL,
    PRIMARY KEY(Id)
);

